// frontend/src/components/file-list.tsx
import React, { useEffect, useMemo, useState } from 'react'
import { Folder, File as FileIcon } from "lucide-react"

export interface FileItem {
  filename: string;
  url: string;
}

interface DirectoryItem {
  name: string;
  path: string;
}

interface DirectoryListingResponse {
  currentPath?: string;
  directories?: DirectoryItem[];
  files?: FileItem[];
}

interface FileListProps {
  endpoint: string;
  onFileSelect: (file: FileItem) => void;
  emptyMessage?: string;
}

export const FileList: React.FC<FileListProps> = ({ 
  endpoint, 
  onFileSelect,
  emptyMessage = "No files available."
}) => {
  const [files, setFiles] = useState<FileItem[]>([])
  const [directories, setDirectories] = useState<DirectoryItem[]>([])
  const [loading, setLoading] = useState<boolean>(false)
  const [error, setError] = useState<string>('')
  const [currentPath, setCurrentPath] = useState<string>('')
  const [resolvedPath, setResolvedPath] = useState<string>('')
  const [initialPathLoaded, setInitialPathLoaded] = useState<boolean>(false)

  const storageKey = useMemo(() => `file-list-path:${endpoint}`, [endpoint])

  // Restore navigation path per endpoint once mounted
  useEffect(() => {
    if (typeof window === 'undefined') {
      return
    }
    setInitialPathLoaded(false)
    const storedPath = window.localStorage.getItem(storageKey) ?? ''
    setCurrentPath(storedPath)
    setResolvedPath(storedPath)
    setInitialPathLoaded(true)
  }, [storageKey])

  useEffect(() => {
    if (!initialPathLoaded) {
      return
    }

    let isActive = true
    const controller = new AbortController()

    const fetchFiles = async () => {
      setLoading(true)
      setError('')
      try {
        const url = currentPath
          ? `${endpoint}?path=${encodeURIComponent(currentPath)}`
          : endpoint
        const response = await fetch(url, { signal: controller.signal })
        console.log(`Fetching from ${url}:`, response)
        if (!response.ok) {
          const error = new Error(`HTTP error! Status: ${response.status}`)
          ;(error as any).status = response.status
          throw error
        }
        const data: DirectoryListingResponse | FileItem[] = await response.json()
        console.log(`Files from ${url}:`, data)
        if (!isActive) {
          return
        }
        if (Array.isArray(data)) {
          // Backwards compatibility with pre-directory listing responses
          setDirectories([])
          setFiles(data)
          setResolvedPath(currentPath)
          if (typeof window !== 'undefined') {
            window.localStorage.setItem(storageKey, currentPath)
          }
        } else {
          setDirectories(data.directories ?? [])
          setFiles(data.files ?? [])
          const nextPath = data.currentPath ?? currentPath
          setResolvedPath(nextPath)
          if (typeof window !== 'undefined') {
            window.localStorage.setItem(storageKey, nextPath)
          }
        }
      } catch (err: any) {
        if (!isActive || err.name === 'AbortError') {
          return
        }
        console.error(`Error fetching files from ${endpoint}:`, err)
        setError(err.message)
        const status = err?.status
        if (status === 404 && currentPath) {
          setCurrentPath('')
          if (typeof window !== 'undefined') {
            window.localStorage.removeItem(storageKey)
          }
        }
      } finally {
        if (isActive) {
          setLoading(false)
        }
      }
    }

    fetchFiles()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [endpoint, currentPath, storageKey, initialPathLoaded])

  const breadcrumbs = useMemo(() => {
    const parts = resolvedPath ? resolvedPath.split('/').filter(Boolean) : []
    const crumbs = [{ label: 'Root', path: '' }]
    parts.forEach((part, index) => {
      const path = parts.slice(0, index + 1).join('/')
      crumbs.push({ label: part, path })
    })
    return crumbs
  }, [resolvedPath])

  const hasEntries = directories.length > 0 || files.length > 0

  return (
    <div>
      <div className="flex flex-wrap items-center gap-1 text-sm text-muted-foreground mb-2">
        {breadcrumbs.map((crumb, index) => (
          <React.Fragment key={`${crumb.label}-${crumb.path || 'root'}`}>
            {index > 0 && <span>/</span>}
            <button
              type="button"
              className="text-blue-600 hover:underline disabled:text-foreground"
              onClick={() => setCurrentPath(crumb.path)}
              disabled={index === breadcrumbs.length - 1}
            >
              {crumb.label || 'Root'}
            </button>
          </React.Fragment>
        ))}
      </div>
      {loading && <p>Loading List...</p>}
      {error && <p style={{ color: 'red' }}>Error: {error}</p>}
      {!loading && !error && (
        hasEntries ? (
          <ul className="space-y-1 text-sm">
            {directories.map((dir) => (
              <li
                key={`dir-${dir.path}`}
                className="flex items-center gap-2 cursor-pointer rounded px-2 py-1 hover:bg-muted"
                onClick={() => setCurrentPath(dir.path)}
              >
                <Folder className="h-4 w-4" />
                <span className="font-medium">{dir.name}</span>
              </li>
            ))}
            {files.map((file, index) => {
              const displayName = file.filename.split('/').pop() ?? file.filename
              return (
                <li
                  key={`file-${file.filename}-${index}`}
                  className="flex items-center gap-2 cursor-pointer rounded px-2 py-1 hover:bg-muted"
                  onClick={() => onFileSelect(file)}
                >
                  <FileIcon className="h-4 w-4" />
                  <span>{displayName}</span>
                </li>
              )
            })}
          </ul>
        ) : (
          <p>{emptyMessage}</p>
        )
      )}
    </div>
  )
}

export default FileList

// frontend-ng/src/app/components/file-list/file-list.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, OnChanges, OnDestroy, OnInit, Output, SimpleChanges } from '@angular/core';
import { DirectoryItem, DirectoryListingResponse, FileItem } from '../../types';

interface Breadcrumb {
  label: string;
  path: string;
}

@Component({
  selector: 'app-file-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './file-list.component.html',
  styleUrls: ['./file-list.component.scss'],
})
export class FileListComponent implements OnInit, OnChanges, OnDestroy {
  @Input() endpoint = '';
  @Input() emptyMessage = 'No files available.';
  @Output() fileSelect = new EventEmitter<FileItem>();

  files: FileItem[] = [];
  directories: DirectoryItem[] = [];
  loading = false;
  error = '';
  currentPath = '';
  resolvedPath = '';

  private initialised = false;
  private abortController?: AbortController;

  ngOnInit(): void {
    this.restorePath();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['endpoint'] && !changes['endpoint'].firstChange) {
      this.restorePath();
    }
  }

  ngOnDestroy(): void {
    this.abortController?.abort();
  }

  get breadcrumbs(): Breadcrumb[] {
    const parts = this.resolvedPath.split('/').filter(Boolean);
    const crumbs: Breadcrumb[] = [{ label: 'Root', path: '' }];
    parts.forEach((part, index) => {
      const path = parts.slice(0, index + 1).join('/');
      crumbs.push({ label: part, path });
    });
    return crumbs;
  }

  navigateTo(path: string): void {
    this.currentPath = path;
    this.fetchFiles();
  }

  selectFile(file: FileItem): void {
    this.fileSelect.emit(file);
  }

  fileLabel(file: FileItem): string {
    const parts = file.filename.split('/');
    return parts[parts.length - 1] || file.filename;
  }

  private restorePath(): void {
    if (!this.endpoint) {
      return;
    }
    const stored = typeof window !== 'undefined'
      ? window.localStorage.getItem(this.storageKey)
      : '';
    this.currentPath = stored ?? '';
    this.resolvedPath = stored ?? '';
    this.initialised = true;
    this.fetchFiles();
  }

  private get storageKey(): string {
    return `file-list-path:${this.endpoint}`;
  }

  private async fetchFiles(): Promise<void> {
    if (!this.endpoint || !this.initialised) {
      return;
    }

    this.abortController?.abort();
    this.abortController = new AbortController();
    this.loading = true;
    this.error = '';

    try {
      const url = this.currentPath
        ? `${this.endpoint}?path=${encodeURIComponent(this.currentPath)}`
        : this.endpoint;
      const response = await fetch(url, { signal: this.abortController.signal });
      if (!response.ok) {
        const error: any = new Error(`HTTP error ${response.status}`);
        error.status = response.status;
        throw error;
      }
      const data: DirectoryListingResponse | FileItem[] = await response.json();
      if (Array.isArray(data)) {
        this.directories = [];
        this.files = data;
        this.resolvedPath = this.currentPath;
      } else {
        this.directories = data.directories ?? [];
        this.files = data.files ?? [];
        this.resolvedPath = data.currentPath ?? this.currentPath;
        this.currentPath = this.resolvedPath;
      }
      if (typeof window !== 'undefined') {
        window.localStorage.setItem(this.storageKey, this.resolvedPath);
      }
    } catch (error: any) {
      if (error.name === 'AbortError') {
        return;
      }
      this.error = error?.message ?? 'Failed to load files';
      if (error?.status === 404) {
        this.currentPath = '';
        if (typeof window !== 'undefined') {
          window.localStorage.removeItem(this.storageKey);
        }
      }
    } finally {
      this.loading = false;
    }
  }
}

<div class="breadcrumbs">
  <ng-container *ngFor="let crumb of breadcrumbs; let i = index">
    <span *ngIf="i > 0" class="sep">/</span>
    <button
      type="button"
      [disabled]="i === breadcrumbs.length - 1"
      (click)="navigateTo(crumb.path)"
    >
      {{ crumb.label || 'Root' }}
    </button>
  </ng-container>
</div>

<div *ngIf="loading" class="status">Loading list…</div>
<div *ngIf="error" class="status error">{{ error }}</div>

<ul *ngIf="!loading && !error && (directories.length || files.length)" class="entry-list">
  <li *ngFor="let dir of directories" (click)="navigateTo(dir.path)">
    <span class="icon">📂</span>
    <span class="label">{{ dir.name }}</span>
  </li>
  <li *ngFor="let file of files" (click)="selectFile(file)">
    <span class="icon">📄</span>
    <span class="label">{{ fileLabel(file) }}</span>
  </li>
</ul>

<p *ngIf="!loading && !error && !directories.length && !files.length" class="status">
  {{ emptyMessage }}
</p>
